# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AddStaged < Formula
  desc "xxx"
  homepage "https://github.com/zcong1993/add-staged"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/add-staged/releases/download/v0.1.0/add-staged_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "beefcc5b2dc9cfe7bdd6018df201f573f69d21eec92ae268cb81e5ff4ac23670"

      def install
        bin.install "add-staged"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/add-staged/releases/download/v0.1.0/add-staged_0.1.0_Darwin_arm64.tar.gz"
      sha256 "51472772c07e9f399e06678587436703be0f15c3825ea3abb0a12626edff4fcb"

      def install
        bin.install "add-staged"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/add-staged/releases/download/v0.1.0/add-staged_0.1.0_Linux_x86_64.tar.gz"
      sha256 "1aa0501e4221be39dd0592ffab5a55cdd33c9de4b8f6c599ec0286a3d962a78d"

      def install
        bin.install "add-staged"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/add-staged/releases/download/v0.1.0/add-staged_0.1.0_Linux_arm64.tar.gz"
      sha256 "2e0e82e83946567b0965f7fc2a6e316ab833399715a4d7502060f5860991dea9"

      def install
        bin.install "add-staged"
      end
    end
  end

  test do
    system "#{bin}/add-staged -v"
  end
end
