# This file was generated by GoReleaser. DO NOT EDIT.
class ChangedFilesRs < Formula
  desc "rust port jest-changed-files"
  homepage "https://github.com/zcong1993/changed-files-rs"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zcong1993/changed-files-rs/archive/v0.1.4.tar.gz"
    sha256 "ca1d9bed37b0277b7ee4b86b5058b0ef8fb167ccea4c3c0642da44964d4de8a4"
  end

  def install
    bin.install "changed-files-rs"
  end

  test do
    system "#{bin}/changed-files-rs -V"
  end
end
