# This file was generated by GoReleaser. DO NOT EDIT.
class ChangedFiles < Formula
  desc "一个让你更方便刷题的工具"
  homepage "https://github.com/zcong1993/changed-files"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zcong1993/changed-files/releases/download/v0.1.0/changed-files_0.1.0_darwin_amd64.tar.gz"
    sha256 "63176b3462af4c367648a694a6008d7423b737ebb0c9aa2c921dda391f2b42f9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zcong1993/changed-files/releases/download/v0.1.0/changed-files_0.1.0_linux_amd64.tar.gz"
    sha256 "09ed606390b1f48ad11b3c3d08909cfc76130f32f458384eb50ecc56ec274389"
  end

  def install
    bin.install "changed-files"
  end

  test do
    system "#{bin}/changed-files -v"
  end
end
