# This file was generated by GoReleaser. DO NOT EDIT.
class ChangedFiles < Formula
  desc "go port jest-changed-files"
  homepage "https://github.com/zcong1993/changed-files"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zcong1993/changed-files/releases/download/v0.1.1/changed-files_0.1.1_darwin_amd64.tar.gz"
    sha256 "8bbd4ce702d322d3ce14295661cb61368dde5c31f8bc9eca71c558547cc1658b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zcong1993/changed-files/releases/download/v0.1.1/changed-files_0.1.1_linux_amd64.tar.gz"
    sha256 "3a3a14e0d58751167343f5235336e15d1735cc862648161e93f4986e15db46ed"
  end

  def install
    bin.install "changed-files"
  end

  test do
    system "#{bin}/changed-files -v"
  end
end
