# This file was generated by GoReleaser. DO NOT EDIT.
class ChangedFilesRs < Formula
  desc "rust port jest-changed-files"
  homepage "https://github.com/zcong1993/changed-files-rs"
  version "0.1.10"

  if OS.mac?
    url "https://github.com/zcong1993/changed-files-rs/releases/download/v0.1.10/changed-files-rs-x86_64-apple-darwin.tar.gz"
    sha256 "7131d8e6650f8456401402856b4be76fd92c17e150722d3c5921749328b21f04"
  end

  def install
    bin.install "changed-files-rs"
  end

  test do
    system "#{bin}/changed-files-rs -V"
  end
end
