# This file was generated by GoReleaser. DO NOT EDIT.
class DownloadRelease < Formula
  desc "Easy download github release"
  homepage "https://github.com/zcong1993/download-release"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zcong1993/download-release/releases/download/v0.1.1/download-release_0.1.1_darwin_amd64.tar.gz"
    sha256 "845704af99d8cdf2a42067e178034c253d5fc3ff235cbb95bc419987fcafb13d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zcong1993/download-release/releases/download/v0.1.1/download-release_0.1.1_linux_amd64.tar.gz"
    sha256 "3fa4af5909efdd5ae01de965ca227a9ca7ddd1f154b7eba63a46b403e26bffa9"
  end

  def install
    bin.install "download-release"
  end

  test do
    system "#{bin}/download-release -h"
  end
end
