# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcommitter < Formula
  desc "Easy way of git commit and push"
  homepage "https://github.com/zcong1993/gcommitter"
  version "2.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/gcommitter/releases/download/v2.2.4/gcommitter_2.2.4_Darwin_arm64.tar.gz"
      sha256 "6eeb696a942b2110a99f25b927d035459c26bd25dde10046f0be3af9379546ed"

      def install
        bin.install "gcommitter"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/gcommitter/releases/download/v2.2.4/gcommitter_2.2.4_Darwin_x86_64.tar.gz"
      sha256 "412746f52553213d5f1630470008dcaf796c0a626865e2145fec4a61a7c19233"

      def install
        bin.install "gcommitter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/gcommitter/releases/download/v2.2.4/gcommitter_2.2.4_Linux_x86_64.tar.gz"
      sha256 "375155211958c3aaea8acfc143c979b45d6d737696f27ee6007d69032842e0df"

      def install
        bin.install "gcommitter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/gcommitter/releases/download/v2.2.4/gcommitter_2.2.4_Linux_arm64.tar.gz"
      sha256 "6bbdbfef9c5e05e220121711c643a6b79fa6b44d9010e1662019a385bd862086"

      def install
        bin.install "gcommitter"
      end
    end
  end

  test do
    system "#{bin}/gcommitter -v"
  end
end
