# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HuskyGo < Formula
  desc "husky git hooks manager in go"
  homepage "https://github.com/zcong1993/husky-go"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.1.1/husky-go_0.1.1_Darwin_arm64.tar.gz"
      sha256 "6e1e35a3d69068828a44e917b92db78e8e83a9a6b00ed1d44caffb426832bc50"

      def install
        bin.install "husky-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.1.1/husky-go_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "86111137917c57f56271f873b0b1f4e4ec541440796b5cdc2f8a4ab348a61eb1"

      def install
        bin.install "husky-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.1.1/husky-go_0.1.1_Linux_arm64.tar.gz"
      sha256 "a5d9b2560f055cca0917ed17b60159ae2238d39b95b32fd06b3be24e72791d3a"

      def install
        bin.install "husky-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.1.1/husky-go_0.1.1_Linux_x86_64.tar.gz"
      sha256 "96a06cb70cf654b275f714adaee2eafb74bd2c9db1310aa1b9941b8cb2c97632"

      def install
        bin.install "husky-go"
      end
    end
  end

  test do
    system "#{bin}/husky-go -v"
  end
end
