# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HuskyGo < Formula
  desc "husky git hooks manager in go"
  homepage "https://github.com/zcong1993/husky-go"
  version "8.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/husky-go/releases/download/v8.0.1/husky-go_8.0.1_Darwin_x86_64.tar.gz"
      sha256 "ee6e6044602a6d6c9fb0224aa8df052bfb88c188b40da7f6bda12a0da43c22fa"

      def install
        bin.install "husky-go"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/husky-go/releases/download/v8.0.1/husky-go_8.0.1_Darwin_arm64.tar.gz"
      sha256 "1edc1250a216bb1fd4311e72367205e2327840aa2bfd82718c4af5fe93a79ef8"

      def install
        bin.install "husky-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/husky-go/releases/download/v8.0.1/husky-go_8.0.1_Linux_arm64.tar.gz"
      sha256 "94789581948876f16b61ca7b74b56b46a8dac07a5bcbc174ead01b8fe9d567ae"

      def install
        bin.install "husky-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/husky-go/releases/download/v8.0.1/husky-go_8.0.1_Linux_x86_64.tar.gz"
      sha256 "745c1620781e9eddaa2201e219bdea67af11d5ae31259fe7d5d957e636deca36"

      def install
        bin.install "husky-go"
      end
    end
  end

  test do
    system "#{bin}/husky-go -v"
  end
end
