# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HuskyGo < Formula
  desc "husky git hooks manager in go"
  homepage "https://github.com/zcong1993/husky-go"
  version "0.8.01"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.8.01/husky-go_0.8.01_Darwin_arm64.tar.gz"
      sha256 "31ca248a48e2a7c3677ace8a79d351faf7dc5ac22bd398ca19fcbdce7738160c"

      def install
        bin.install "husky-go"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.8.01/husky-go_0.8.01_Darwin_x86_64.tar.gz"
      sha256 "0196da6926bfca7d511660d0e309de4c4444c8656530b463b1bd33a9e198e1d2"

      def install
        bin.install "husky-go"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.8.01/husky-go_0.8.01_Linux_x86_64.tar.gz"
      sha256 "6ba0d171c30386e4bf47192e4a7a4ce56d673ce0d1988ecb4435d5f0aff90fac"

      def install
        bin.install "husky-go"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/husky-go/releases/download/v0.8.01/husky-go_0.8.01_Linux_arm64.tar.gz"
      sha256 "3e84d83442b01b959e9e521268bdc8b72aa50b0866e828b4ab1a6555dc46f678"

      def install
        bin.install "husky-go"
      end
    end
  end

  test do
    system "#{bin}/husky-go -v"
  end
end
