# This file was generated by GoReleaser. DO NOT EDIT.
class LeetcodeTool < Formula
  desc "一个让你更方便刷题的工具"
  homepage "https://github.com/zcong1993/leetcode-tool"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zcong1993/leetcode-tool/releases/download/v0.1.3/leetcode-tool_0.1.3_darwin_amd64.tar.gz"
    sha256 "e9fe21dc1713965f376370473ecb872771cc946a91baddfde47e7f44870708be"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/leetcode-tool/releases/download/v0.1.3/leetcode-tool_0.1.3_linux_amd64.tar.gz"
      sha256 "98bf1068acbdd2d9042df0399e01b96ffe9cc03aa21a8af57651f0c90ca17b89"
    end
  end

  def install
    bin.install "leetcode-tool"
  end

  test do
    system "#{bin}/leetcode-tool -v"
  end
end
