# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeetcodeTool < Formula
  desc "一个让你更方便刷题的工具"
  homepage "https://github.com/zcong1993/leetcode-tool"
  version "0.4.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/leetcode-tool/releases/download/v0.4.1/leetcode-tool_0.4.1_darwin_amd64.tar.gz"
      sha256 "a7487312872c0ae8dce624a6154b44a179aec2bd4fb3dd8daf07c1d369920458"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/leetcode-tool/releases/download/v0.4.1/leetcode-tool_0.4.1_linux_amd64.tar.gz"
      sha256 "ea3336641107e787cd92cf08aaf76eefe6ab6ca1c264254845c0be0a12958b2d"
    end
  end

  def install
    bin.install "leetcode-tool"
  end

  test do
    system "#{bin}/leetcode-tool -v"
  end
end
