# This file was generated by GoReleaser. DO NOT EDIT.
class LeetcodeTool < Formula
  desc "一个让你更方便刷题的工具"
  homepage "https://github.com/zcong1993/leetcode-tool"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/zcong1993/leetcode-tool/releases/download/v0.2.0/leetcode-tool_0.2.0_darwin_amd64.tar.gz"
    sha256 "3d59f6b310a531104d4ff0f99b8c54a385b2bdbc47d5206a05b15dffd4836f6f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/zcong1993/leetcode-tool/releases/download/v0.2.0/leetcode-tool_0.2.0_linux_amd64.tar.gz"
    sha256 "db6e05c7076c08f5e6a0ee0f730f6ceda9ff4591a4b0f5acd36246adc97a03dd"
  end

  def install
    bin.install "leetcode-tool"
  end

  test do
    system "#{bin}/leetcode-tool -v"
  end
end
