# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RssWatcher < Formula
  desc "Watch rss source"
  homepage "https://github.com/zcong1993/rss-watcher"
  version "0.20.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.20.0/rss-watcher_0.20.0_Darwin_x86_64.tar.gz"
      sha256 "202813293e86ab52792dd9f13fa19a26666ea9a6a87477f0281f9a08ebcd0f87"
    end
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.20.0/rss-watcher_0.20.0_Darwin_arm64.tar.gz"
      sha256 "b71bbef65a74bd8dfdd3ff53a2d5e41029cb9431fc3607cd040c8fda06d95289"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.20.0/rss-watcher_0.20.0_Linux_x86_64.tar.gz"
      sha256 "70a4c2575ddb2fd14ac15f155cc193a4fa574451d99bce8167dc4011da19b6a8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.20.0/rss-watcher_0.20.0_Linux_arm64.tar.gz"
      sha256 "c6a6a8991c264d3f33d6f9fc24b3a23d5a6181e6aa40b8eb441faefb7faf3d47"
    end
  end

  def install
    bin.install "rss-watcher"
  end

  test do
    system "#{bin}/rss-watcher --version"
  end
end
