# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RssWatcher < Formula
  desc "Watch rss source"
  homepage "https://github.com/zcong1993/rss-watcher"
  version "0.22.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.22.2/rss-watcher_0.22.2_Darwin_arm64.tar.gz"
      sha256 "4ea63bafba387694fd033b58f30f89b13d520e7bd93283c6d1efe2f99218d0ef"

      def install
        bin.install "rss-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.22.2/rss-watcher_0.22.2_Darwin_x86_64.tar.gz"
      sha256 "bda156e4f037a4a5b707c68018d53e0ca9f36955c767f9ce018db469418e67d9"

      def install
        bin.install "rss-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.22.2/rss-watcher_0.22.2_Linux_arm64.tar.gz"
      sha256 "8229cc5c03dd8e6f470b59e295e75c34d3fddb7f96102fdca4f7a10815d1e655"

      def install
        bin.install "rss-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zcong1993/rss-watcher/releases/download/v0.22.2/rss-watcher_0.22.2_Linux_x86_64.tar.gz"
      sha256 "6e69624992511f480d1d74e46d8de851b9ab69dc3297cda8428265577d88f9e3"

      def install
        bin.install "rss-watcher"
      end
    end
  end

  test do
    system "#{bin}/rss-watcher --version"
  end
end
